unix {cli-listen /run/vpp/cli-vpp1.sock}
api-segment { prefix vpp1 }
plugins { plugin dpdk_plugin.so { disable } }

socksvr { socket-name /run/vpp/api1.sock }
statseg { socket-name /run/vpp/stats1.sock }
