unix {cli-listen /run/vpp/cli-vpp1.sock}
api-segment {
    prefix vpp1 
#shm  /run/vpp/api1-shm
#    prefix /run/vpp/api1-shm
}
plugins { 
    plugin dpdk_plugin.so { disable } 
    plugin af_packet_plugin.so { enable }
}

socksvr { 
    socket-name /run/vpp/api1.sock 
#use-blocking-socket on
}
statseg { socket-name /run/vpp/stats1.sock }
